---
- name: Example of provisioning servers
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: ep2
        description: Access to the Episode2 servers
        region: us-west-2
        vpc_id: vpc-551b523d
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch instances
      local_action:
        module: ec2
        region: us-west-2
        keypair: answersforaws
        group: ep2
        instance_type: m1.small
        image: ami-8635a9b6
        vpc_subnet_id: subnet-941b52fc
        count: 2
        wait: yes
      register: ec2

    - name: Add EP2 instances to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=ep2
      with_items: ec2.instances

    - name: Add tag to instances
      local_action: ec2_tag resource={{ item.id }} region=us-west-2 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: EP2

    - name: Wait for SSH to be available
      pause: minutes=1


- name: Configure provisioned servers
  hosts: ep2
  user: ubuntu
  sudo: True
  tasks:
    